### ISSUE TITLE
[ENHANCEMENT]: When watching a video, the creator of the video must be clickable (to go to his profile page)

### ISSUE THREAD

**Issue by sylvain-reynaud** [polyflix/frontend#30]
### Description

When watching a video, the creator of the video must be clickable (to go to his profile page)

fast example: https://polyflix.dopolytech.fr/videos/trust-by-verify-nicolas-muller-nicolas-tournier-polycloud-2022-4rx7M

![image](https://user-images.githubusercontent.com/20583601/204410192-b62a9407-c5b9-4b90-ab5b-e79281771238.png)

**Comment by hugoamalric** [comment]
Already implemented.
