### ISSUE TITLE
[FEAT]: Add certificate section to user profile

### ISSUE THREAD

**Issue by mflagey** [polyflix/frontend#9]
### Description

![image](https://user-images.githubusercontent.com/61873164/203055309-d9f9ff02-a2cb-480d-8544-9ec45ffb80e4.png)

Add section to profile page to see user's certificates

**Comment by LeoFVO** [comment]
Already implemented.



![Image](https://user-images.githubusercontent.com/58391988/204585494-9aa80fc0-d609-4429-b241-576bb96bd779.png)
